version: '3'
services:
  react_client:
    build:
      context: ./client
    ports:
      - "8002:3000" # Stellt sicher, dass der Client auf Port 80 des Hosts verfügbar ist
    networks:
      - ai_network
    environment:
      - RUNNING_IN_DOCKER=true
  python_server:
    build:
      context: ./server
    environment:
      - PORT=5000
    networks:
      - ai_network

networks:
  ai_network:
